[features]
seeds = false
[programs.localnet]
backend = "9ibCEh3Fb39Q9cDAjSamePo2bY3BdU6fXRfSWjVLyUqo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/isaacrestrick/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
